from scrapy import Item, Field

class DigimonItem(Item):
    name = Field()
    original_name = Field()
    image = Field()
    url = Field()
    title = Field()
    level = Field()
    digi_types = Field()
    attributes = Field()
    family = Field()
    size = Field()
    debut = Field()
    slide_forms = Field()
    prior_forms = Field()
    next_forms = Field()
    partners = Field()
    voice_actors = Field()
    cards = Field()
    other_names = Field()
    variations = Field()
    groups = Field()
